<body>
    <font color=#010000> During World War II, invisible inks offered a <br/>
    <font color=#000001> common form of invisible writing. With the <br/>
    <font color=#000111> invisible ink, a seemingly innocent letter could <br/>
    <font color=#00000D> contain a very different message written between <br/>
    <font color=#010D0D> the lines. Therefore, the document text can conceal a <br/>
    <font color=#000B1B> hidden message through the use of null ciphers <br/>
    <font color=#0D0C00> (unencrypted message), which perfectly camouflage <br/>
    <font color=#01010E> the real message in an ordinary letter. Open-coded <br/>
    <font color=#010101> messages in which are plain text passages, but they <br/>
    <font color=#000000> are shown in only ordinary occurrence. The suspect <br/>
    <font color=#011001> communication can be detected by mail filters while <br/>
    <font color=#000000> “innocent” messages are allowed to flow through. <br/>
    <font color=#000011> There is an example on one of the most significant <br/>
    <font color=#000000> null cipher messages sent by a Nazi spy: <br/>
    <font color=#000000> "Apparently neutral’s protest is thoroughly <br/>
    <font color=#001101> discounted and ignored. Isman hard hit. Blockade <br/>
    <font color=#000000> issue affects pretext for embargo on by-products, <br/>
    <font color=#000111> ejecting suets and vegetable oils". <br/>
    <font color=#000000> By extracting the second letter from each word, this <br/>
    <font color=#0D0C01> hidden message can be decoded as: <br/>
    <font color=#000000> "Pershing sails from NY June 1". <br/>
</body>